# 进退群通知
accept:
  BlackGroup:
    - "636023444"
  cd: 30

# 上下班
NoWork:
  - "636023444"

# 进群验证
Test:
  - "114514"
# 群/好友请求处理
DealRequest:
  # 处理拉群邀请
  InvitedJoinGroup:
    # 自动接受邀请
    accept: false
    # 给所有主人发送通知
    notify: true
  # 处理好友请求
  Friend:
    accept: false
    notify: true
  # 处理入群请求
  Group:
    # 支持指定若干群启用，指定后为白名单模式，只有在列表中的群才会被处理
    - "12345":
        accept: false
        notify: true
    # 支持全局设置，不指定群号则为全局设置
    # accept: false
    # notify: true
